// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: setup.sql

package database

import (
	"context"
)

const checkAdmin = `-- name: CheckAdmin :one
SELECT completed FROM setup WHERE id = 1
`

func (q *Queries) CheckAdmin(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkAdmin)
	var completed bool
	err := row.Scan(&completed)
	return completed, err
}

const markAdminAsCreated = `-- name: MarkAdminAsCreated :exec
UPDATE setup SET completed = TRUE WHERE id = 1
`

func (q *Queries) MarkAdminAsCreated(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markAdminAsCreated)
	return err
}
