// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, name, email, api_key, usertype)
VALUES ($1, $2, $3, $4, $5,
    encode(sha256(random()::text::bytea), 'hex'),
    $6
)
RETURNING id, created_at, updated_at, name, email, api_key, usertype
`

type CreateUserParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Email     string
	Usertype  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Email,
		arg.Usertype,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.ApiKey,
		&i.Usertype,
	)
	return i, err
}

const gerUserByAPIKey = `-- name: GerUserByAPIKey :one
SELECT id, created_at, updated_at, name, email, api_key, usertype FROM users WHERE api_key = $1
`

func (q *Queries) GerUserByAPIKey(ctx context.Context, apiKey string) (User, error) {
	row := q.db.QueryRowContext(ctx, gerUserByAPIKey, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.ApiKey,
		&i.Usertype,
	)
	return i, err
}
